productName: "Search Engine"
productNumber: "CXC 201 1191"
images:
  searchengine:
    productName: "eric-data-search-engine"
    productNumber: "CXU 101 0644"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "proj-adp-log-released"
    name: "eric-data-search-engine"
    tag: "7.0.0-25"
  bragent:
    productName: "eric-data-search-engine-br-agent"
    productNumber: "CXU 101 0645"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "proj-adp-log-released"
    name: "eric-data-search-engine-br-agent"
    tag: "7.0.0-25"
  metrics:
    productName: "eric-data-search-engine-pm-metrics"
    productNumber: "CXU 101 0646"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "proj-adp-log-released"
    name: "eric-data-search-engine-pm-metrics"
    tag: "7.0.0-25"
  tlsproxy:
    productName: "eric-data-search-engine-tls-proxy"
    productNumber: "CXU 101 0194"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "proj-adp-log-released"
    name: "eric-data-search-engine-tls-proxy"
    tag: "7.0.0-25"
  logshipper:
    productName: "eric-log-shipper"
    productNumber: ""
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "proj-adp-log-released"
    name: "eric-log-shipper"
    tag: "5.9.0-14"