apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "eric-enm-es-benchmark.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: {{ include "eric-enm-es-benchmark.storageClass" . }}
