apiVersion: v1
kind: Service
metadata:
  name: {{$.Chart.Name}}
  labels:
    app.kubernetes.io/name: {{$.Chart.Name}}
spec:
  type: ClusterIP
  selector: 
    app.kubernetes.io/component: es-orchestrator
  ports:
    - name: http
      protocol: TCP
      port: {{ include "orchestrator.http.port" . }}
      targetPort: {{ include "orchestrator.http.port" . }}